### ISSUE TITLE
Segfault on call to hipblasCreate

### ISSUE THREAD

**Issue by colleeneb** [CHIP-SPV/H4I-HipBLAS#18]
With the latest from chipStar, MKLShim, and hipBLAS commits:

chipStar: https://github.com/CHIP-SPV/chipStar/commit/27c450d2e98efa6d5030e85555532d4608f98daa
MKLShim: https://github.com/CHIP-SPV/H4I-MKLShim/commit/23c5f52f09946795e684194f882ddb4a00b97313
hipBLAS: https://github.com/CHIP-SPV/H4I-HipBLAS/commit/b8b2486cdac844ab7ca29747ff657e62d670f641

I see a segfault in a call in a simple code that just calls `hipblasCreate`:
```
#include "hipblas.h"
#include <iostream>
#include <limits>
#include <stdio.h>
#include <stdlib.h>
#include <vector>

int main()
{
    hipblasHandle_t handle;
    hipblasCreate(&handle);

}
```

 This code has worked in the past, but it is not working now. With gdb, the backtrace is:
```
#0  0x0000155554972c6b in raise () from /lib64/libc.so.6
#1  0x0000155554974305 in abort () from /lib64/libc.so.6
#2  0x0000155554f2e675 in ?? () from /usr/lib64/libstdc++.so.6
#3  0x0000155554f39d0c in ?? () from /usr/lib64/libstdc++.so.6
#4  0x0000155554f39d77 in std::terminate() () from /usr/lib64/libstdc++.so.6
#5  0x0000155554f39fd8 in __cxa_throw () from /usr/lib64/libstdc++.so.6
#6  0x0000155529664001 in void sycl::_V1::detail::plugin::checkPiResult<sycl::_V1::runtime_error>(_pi_result) const () from /opt/aurora/23.275.2/oneapi/compiler/latest/lib/libsycl.so.7
#7  0x00001555296619de in sycl::_V1::ext::oneapi::level_zero::make_device(sycl::_V1::platform const&, unsigned long) () from /opt/aurora/23.275.2/oneapi/compiler/latest/lib/libsycl.so.7
#8  0x00001555554c4168 in H4I::MKLShim::Update(H4I::MKLShim::Context*, unsigned long const*, int, char const*) () from /home/bertoni/projects/p12.chipStar/MKL/H4I-MKLShim/build/packages/lib64/libMKLShim.so
#9  0x00001555554c51bb in H4I::MKLShim::Create(unsigned long const*, int, char const*) ()
   from /home/bertoni/projects/p12.chipStar/MKL/H4I-MKLShim/build/packages/lib64/libMKLShim.so
#10 0x000015555548880f in hipblasCreate ()
   from /home/bertoni/projects/p12.chipStar/MKL/H4I-HipBLAS/build/packages//lib64/libhipblas.so
#11 0x0000555555555db6 in main ()
(gdb) 
```

Maybe this is related to the backend handle refactor (https://github.com/CHIP-SPV/chipStar/pull/789)? Or please let me know if something I'm running looks incorrect. Thanks!

**Comment by colleeneb** [comment]
Resolved with [08132fde814fdf25dc4ce9f3a3351d5a46663209](https://github.com/CHIP-SPV/H4I-MKLShim/commit/08132fde814fdf25dc4ce9f3a3351d5a46663209) Thanks @pvelesko !
